# Generated by Django 3.0.6 on 2020-08-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='update',
            new_name='updated',
        ),
    ]
